# Generated by Django 4.2.9 on 2024-01-15 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('second_name', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
                ('tel', models.IntegerField()),
                ('upload_images', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
